const $=x=>document.getElementById(x);let reports=JSON.parse(localStorage.tagelohn||'[]');
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0)}
function today(){return new Date().toISOString().slice(0,10)}
function addEmp(e={}){let d=document.createElement('div');d.className='employee';d.innerHTML=`<button class="del">Löschen</button><b>Mitarbeiter</b><div class="grid"><label>Stunden<input class="hours" type="number" step=".25" value="${e.hours||0}"></label><label>Art der Tätigkeit<input class="activity" value="${e.activity||''}"></label></div><label>Name des Mitarbeiters<input class="name" value="${e.name||''}"></label><div class="grid grid3"><label>Anfang<input class="start" type="time" value="${e.start||''}"></label><label>Ende<input class="end" type="time" value="${e.end||''}"></label><label>Pause<input class="pause" type="number" value="${e.pause||0}"></label></div>`;d.querySelector('.del').onclick=()=>d.remove();['start','end','pause'].forEach(c=>d.querySelector('.'+c).oninput=()=>calc(d));$('employees').append(d)}
function calc(d){let s=d.querySelector('.start').value,e=d.querySelector('.end').value,p=+(d.querySelector('.pause').value||0);if(s&&e){let a=s.split(':').map(Number),b=e.split(':').map(Number),m=b[0]*60+b[1]-a[0]*60-a[1]-p;if(m>=0)d.querySelector('.hours').value=(m/60).toFixed(2)}}
function item(id,v=''){let d=document.createElement('div');d.className='item';d.innerHTML=`<input value="${v}"><button class="del">×</button>`;d.querySelector('button').onclick=()=>d.remove();$(id).append(d)}
function fill(r){$('date').value=r.date||today();$('contractor').value=r.contractor||'Dreyer Hochbau GmbH & Co. KG';$('address').value=r.address||'Mühlenberg 12\n2404 Elsdorf';$('project').value=r.project||'Rohrleitungsarbeiten Betriebsgelände Elsdorf';$('client').value=r.client||'';$('employees').innerHTML='';(r.employees||[]).forEach(addEmp);$('works').innerHTML='';(r.works||[]).forEach(v=>item('works',v));$('materials').innerHTML='';(r.materials||[]).forEach(v=>item('materials',v))}
function collect(){return{date:$('date').value,contractor:$('contractor').value,address:$('address').value,project:$('project').value,client:$('client').value,employees:[...document.querySelectorAll('.employee')].map(d=>({hours:+d.querySelector('.hours').value,activity:d.querySelector('.activity').value,name:d.querySelector('.name').value,start:d.querySelector('.start').value,end:d.querySelector('.end').value,pause:+d.querySelector('.pause').value})),works:[...document.querySelectorAll('#works input')].map(x=>x.value).filter(Boolean),materials:[...document.querySelectorAll('#materials input')].map(x=>x.value).filter(Boolean),signature:$('sig').toDataURL()}}
function save(){localStorage.tagelohn=JSON.stringify(reports);$('count').textContent=reports.length+' Nachweis'+(reports.length==1?'':'e')}
function render(){let l=$('list');l.innerHTML=reports.length?'':'<div class="panel">Noch keine Nachweise gespeichert.</div>';reports.forEach((r,i)=>{let d=document.createElement('div');d.className='archive';d.innerHTML=`<b>${r.date}</b><br>${r.project}<small>${r.contractor}</small><br><button>Öffnen</button>`;d.querySelector('button').onclick=()=>{fill(r);show('editor')};l.append(d)})}
$('new').onclick=$('new2').onclick=()=>{fill({});show('editor')};$('addEmp').onclick=()=>addEmp();$('addWork').onclick=()=>item('works');$('addMat').onclick=()=>item('materials');$('archiveBtn').onclick=()=>{render();show('archive')};$('homeBtn').onclick=()=>show('home');$('save').onclick=()=>{reports.unshift(collect());save();render();show('archive')};$('pdf').onclick=()=>alert('PDF-Vorschau vorbereitet. Im nächsten Schritt wird die Original-PDF 1:1 als Hintergrund eingebunden.');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.s));save();

let c=$('sig'),ctx=c.getContext('2d'),down=false;c.onpointerdown=e=>{down=true;ctx.beginPath();let p=pos(e);ctx.moveTo(p.x,p.y)};c.onpointermove=e=>{if(!down)return;let p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()};window.onpointerup=()=>down=false;function pos(e){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}$('clear').onclick=()=>ctx.clearRect(0,0,c.width,c.height);